def default_profile(name: str, tags: list[str]) -> dict[str, object]:
    return {
        "name": name,
        "tags": tags,
        "browserType": "anty",
        "mainWebsite": "",
        "deviceName": {"mode": "off", "value": None},
        "macAddress": {"mode": "random", "value": None},
        "webrtc": {"mode": "altered", "ipAddress": None},
        "canvas": {"mode": "noise"},
        "webgl": {"mode": "noise"},
        "webgpu": {"mode": "real"},
        "clientRect": {"mode": "noise"},
        "timezone": {"mode": "auto", "value": None},
        "locale": {"mode": "auto", "value": None},
        "proxy": None,
        "geolocation": {
            "mode": "auto",
            "latitude": None,
            "longitude": None,
            "accuracy": None,
        },
        "audio": {"mode": "real"},
        "mediaDevices": {
            "mode": "real",
            "audioInputs": None,
            "videoInputs": None,
            "audioOutputs": None,
        },
        "ports": {
            "mode": "protect",
            "blacklist": "3389,5900,5800,7070,6568,5938",
        },
        "doNotTrack": False,
        "args": [],
        "login": "",
        "password": "",
        "vendorSub": "",
    }
